### ISSUE TITLE
Prettier issues

### ISSUE THREAD

**Issue by maraisr** [schmod/babel-plugin-angularjs-annotate#25]
Hi, so [prettier](https://github.com/prettier/prettier) adds a wrapping bracket to the string `('ngInject')` . Which isn't compiling correctly.

```ts
class Foo {

  constructor(private $http) {
    ('ngInject');

    this.$http; // undefined
  }
}
```

TypeScript -> es2017 -> Babel -> es5.

Can you please direct me to the line / file I'll need to edit to make this mod. Could be a root `ng-annotate` issue?

**Comment by schmod** [comment]
Hi @maraisr:  

[I've tried out this code snippet on Prettier's REPL](https://prettier.io/#%7B%22content%22%3A%22class%20Foo%20%7B%5Cn%20%20constructor(%24http)%20%7B%5Cn%20%20%20%20'ngInject'%3B%5Cn%20%20%20%20this.%24http%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D), and (apart from the lack of support for the `private` keyword), I'm not seeing Prettier adding any parentheses.  TypeScript also [doesn't seem to have a problem](https://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%0D%0A%20%20constructor(private%20%24http)%20%7B%0D%0A%20%20%20%20'ngInject'%3B%0D%0A%0D%0A%20%20%20%20this.%24http%3B%20%2F%2F%20undefined%0D%0A%20%20%7D%0D%0A%7D) with it.

The `'ngInject';` string used in your example is called a [Prologue Directive](https://www.ecma-international.org/ecma-262/5.1/#sec-14.1), and is a part of the ECMAScript language specification.  Wrapping parentheses around the string fundamentally changes its meaning to the parser, which is why we're not picking it up.

I'm going to close this issue because whatever variant of Prettier that you're using is going to need to be fixed to properly support prologue directives.
