### ISSUE TITLE
Add support for the explicit-only mode

### ISSUE THREAD

**Issue by mgol** [schmod/babel-plugin-angularjs-annotate#4]
The implicit mode has many potential surprises; I'd like to be able to explicitly mark all places that should be annotated and have a guarantee nothing else gets annotated. In this mode only classes/functions marked with `/* @ngInject */` or `'ngInject';` would be annotated.

**Comment by schmod** [comment]
👍 

Seems reasonable, and shouldn't be terribly difficult to implement.  I'll see what I can do.

**Comment by schmod** [comment]
Is there any benefit of being able to individually enable/disable the `/* @ngInject */` and `'ngInject` matchers, or will it be sufficient to add a toggle that disables implicit matches?

**Comment by mgol** [comment]
I think disabling all implicit matches should be enough (at least it would for me); disabling one explicit annotation style is more a job for a linter if someone wants sth like that.

**Comment by schmod** [comment]
While looking at the existing test cases, I stumbled across this:

```js
/* @ngInject */
function MyDirective2($stateProvider) {
    $stateProvider.state('astate', {
        resolve: {
            yoyo: function(ma) {
            },
        }
    });
}
```

When we're doing "explicit-only" annotating, I think it's reasonable to assume that the above code sample would _not_ work correctly, unless an additional `/* @ngInject */` or `'ngInject'` was added to `yoyo`.

When we add an `ngInject` annotation to a node, I don't think that our users should assume that implicit matching will be enabled for anything inside that node.  (Implementing this would be difficult, and IMO, the results could be unpredictable).

I don't really have a question about this... just wanted to write it down somewhere so that it can come back to haunt me later on.
